import "./globals.css";
export const dynamic = 'force-dynamic'

export const metadata = {
  title: "SMS Catcher",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
